---
spring:
  profiles: web
  application.name: micro-web

server:
  port: 8080

eureka.client:
  register-with-eureka: false

extension:
  security:
    auth:
      enabled: false
      admin: false
    cors.enabled: true
  mail.enabled: false
  remoting:
    app: micro-app
    asset: micro-asset

---
spring:
  profiles: admin

server.port: 8081

extension: 
  security.auth.admin: true
