---
spring:
  profiles: asset
  application.name: micro-asset

server:
  port: 8100

extension:
  datasource:
    asset:
      url: jdbc:h2:tcp://localhost:9092/mem:asset
      username:
      password:
      jpa:
        package-to-scan: sample.microasset.model.asset
        hibernate.ddl-auto: create-drop
  datafixture.enabled: true

 