---
spring:
  application.name: micro-registry
  aop.proxy-target-class: true
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

banner.location: banner.txt

server:
  port: 8761

security:
  user.password: unused
  basic.enabled: false

management:
  context-path: /api/management
  security.enabled: false

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

extension.test.db.enabled: true

---
spring:
  profiles: production

management.security.enabled: true

extension:
  security.cors.enabled: false
  test.db.enabled: false
