---
spring:
  profiles: app
  application.name: micro-app
  boot.admin:
    discovery.converter.management-context-path: ${management.context-path}

server:
  port: 8090

extension:
  hibernate:
    default.createDrop: true
    system.createDrop: true
  datafixture.enabled: true
